import Head from 'next/head';
import { Orbitron } from 'next/font/google';
import { use, useEffect, useState } from 'react';
import Select from 'react-select';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import styles from '@/styles/Home.module.scss';
import axios from 'axios';
import { collection, addDoc } from 'firebase/firestore';

import {
  getCountriesFunction,
  getTagsFunction,
  getRadioStationsByCountryFunction,
  getRadioStationsByTagFunction,
  getLanguagesFunction,
  getRadioStationByLanguageFunction,
} from '../utils/functionsApi';
import { handleCountry, handleSelect } from '@/utils/functions';
import Loading from '@/components/Loading';
import Radio from '@/components/Radio';

const orbitron = Orbitron({
  subsets: ['latin'],
  weight: '500',
});
const firebase = require('firebase');
// Required for side-effects
require('firebase/firestore');

export default function Home() {
  const [channels, setChannels] = useState([]);
  const [countryOptions, setCountryOptions] = useState([]);
  const [tagsOption, setTagsOption] = useState([]);
  const [languagesOption, setLanguagesOption] = useState([]);
  const [station, setStation] = useState(0);
  const [control, setControl] = useState(false);
  const [selectedCountry, setSelectedCountry] = useState(null);
  const [selectedTag, setSelectedTag] = useState(null);
  const [selectedLanguage, setSelectedLanguage] = useState(null);
  const [playingStation, setPlayingStation] = useState(null);
  const getOptionLabel = (option) => option.label;

  const handleCheckPlaying = (event) => {
    const audioElement = event.target;
    setControl(!audioElement.paused);
  };

  useEffect(() => {
    getCountriesFunction(setCountryOptions);
    getTagsFunction(setTagsOption);
    getLanguagesFunction(setLanguagesOption);
  }, []);

  useEffect(() => {
    selectedCountry !== null &&
      getRadioStationsByCountryFunction(setChannels, selectedCountry);
  }, [selectedCountry]);

  useEffect(() => {
    selectedLanguage !== null &&
      getRadioStationByLanguageFunction(setChannels, selectedLanguage);
  }, [selectedLanguage]);

  useEffect(() => {
    selectedTag !== null &&
      getRadioStationsByTagFunction(setChannels, selectedTag);
  }, [selectedTag]);

  useEffect(() => {
    channels?.length !== 0 && setPlayingStation(channels?.[station]?.name);
  }, [channels, station]);

  axios
    .post('https://645934634eb3f674df8a0649.mockapi.io/api/v1/stations', [
      {
        changeuuid: '610cafba-71d8-40fc-bf68-1456ec973b9d',
        stationuuid: '941ef6f1-0699-4821-95b1-2b678e3ff62e',
        serveruuid: null,
        name: '\tBest FM',
        url: 'http://stream.bestfm.sk/128.mp3',
        url_resolved: 'http://stream.bestfm.sk/128.mp3',
        homepage: 'http://bestfm.sk/',
        favicon: '',
        tags: '',
        country: 'Slovakia',
        countrycode: 'SK',
        iso_3166_2: null,
        state: '',
        language: '',
        languagecodes: '',
        votes: 29,
        lastchangetime: '2022-11-01 08:42:32',
        lastchangetime_iso8601: '2022-11-01T08:42:32Z',
        codec: 'MP3',
        bitrate: 128,
        hls: 0,
        lastcheckok: 1,
        lastchecktime: '2023-05-07 20:14:39',
        lastchecktime_iso8601: '2023-05-07T20:14:39Z',
        lastcheckoktime: '2023-05-07 20:14:39',
        lastcheckoktime_iso8601: '2023-05-07T20:14:39Z',
        lastlocalchecktime: '',
        lastlocalchecktime_iso8601: null,
        clicktimestamp: '2023-05-08 09:53:58',
        clicktimestamp_iso8601: '2023-05-08T09:53:58Z',
        clickcount: 49,
        clicktrend: -4,
        ssl_error: 0,
        geo_lat: null,
        geo_long: null,
        has_extended_info: false,
      },
    ])
    .then((response) => {
      console.log(response);
    })
    .catch((error) => {
      console.log(error);
    });

  return (
    <>
      <Head>
        <title>Vintage Vibe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.wrapper} ${orbitron.className}`}>
        <ToastContainer pauseOnHover theme="colored" />
        <div className={styles.loaderWrapper}>
          {control === false &&
            (selectedCountry !== null ||
              selectedLanguage !== null ||
              selectedTag !== null) && <Loading />}
        </div>
        <div className={styles.imageWrapper}>
          <Radio
            setStation={setStation}
            station={station}
            playingStation={playingStation}
            channels={channels}
          />
          <section className={styles.list}>
            <Select
              options={countryOptions}
              className={styles.select}
              placeholder="Countries"
              onChange={(value) =>
                handleSelect(
                  value.label,
                  setSelectedCountry,
                  setSelectedLanguage,
                  setSelectedTag
                )
              }
              value={{
                value: selectedCountry,
                label: selectedCountry === null ? 'Countries' : selectedCountry,
              }}
              getOptionLabel={getOptionLabel}
            />
            <Select
              options={tagsOption}
              className={styles.select}
              placeholder="Tags"
              value={{
                value: selectedTag,
                label: selectedTag === null ? 'Tags' : selectedTag,
              }}
              getOptionLabel={getOptionLabel}
              onChange={(value) =>
                handleSelect(
                  value.label,
                  setSelectedTag,
                  setSelectedCountry,
                  setSelectedLanguage
                )
              }
            />
            <Select
              options={languagesOption}
              className={styles.select}
              placeholder="Languages"
              value={{
                value: selectedLanguage,
                label:
                  selectedLanguage === null ? 'Languages' : selectedLanguage,
              }}
              getOptionLabel={getOptionLabel}
              onChange={(value) =>
                handleSelect(
                  value.label,
                  setSelectedLanguage,
                  setSelectedTag,
                  setSelectedCountry
                )
              }
            />
          </section>
        </div>

        <audio
          src={channels?.[station]?.url}
          autoPlay
          controls
          className={styles.audio}
          onTimeUpdate={handleCheckPlaying}
          // type="audio/mpeg"
        ></audio>
      </main>
    </>
  );
}
